exports.quotesArray = [
    {qoute: 'Run when you can, walk if you have to, crawl if you must; just never give up.', author: "Dean Karnazes"},
    {qoute: 'I don’t run to add days to my life, I run to add life to my days.', author: "Ronald Rook"},
    {qoute: 'The point is whether or not I improved over yesterday. In long-distance running the only opponent you have to beat is yourself, the way you used to be.', author: "Haruki Murakami"},
    {qoute: 'Every morning in Africa, a gazelle wakes up, it knows it must outrun the fastest lion or it will be killed. Every morning in Africa, a lion wakes up. It knows it must run faster than the slowest gazelle, or it will starve. It doesn’t matter whether you’re the lion or a gazelle – when the sun comes up, you’d better be running.', author: "Haruki Murakami"},
    {qoute: 'I’ll be happy if running and I can grow old together.', author: "Haruki Murakami"},
    {qoute: 'Running is about finding your inner peace, and so is a life well lived.', author: "Dean Karnazes"},
    {qoute: 'For me, running is both exercise and a metaphor. Running day after day, piling up the races, bit by bit I raise the bar, and by clearing each level I elevate myself.', author: "Haruki Murakami"},
    {qoute: 'Running! If there’s any activity happier, more exhilarating, more nourishing to the imagination, I can’t think of what it might be. In running the mind flees with the body, the mysterious efflorescence of language seems to pulse in the brain, in rhythm with our feet and the swinging of our arms.', author: "Joyce Carol Oates"},
    {qoute: 'I run because if I didn’t, I’d be sluggish and glum and spend too much time on the couch. I run to breathe the fresh air. I run to explore. I run to escape the ordinary. I run…to savor the trip along the way. Life becomes a little more vibrant, a little more intense. I like that.', author: "Dean Karnazes"},
    {qoute: 'Pain is inevitable. Suffering is optional.', author: "Haruki Murakami"},
    {qoute: 'Some seek the comfort of their therapist’s office, other head to the corner pub and dive into a pint, but I chose running as my therapy.', author: "Dean Karnazes"},
    {qoute: 'Struggling and suffering are the essence of a life worth living. If you’re not pushing yourself beyond the comfort zone, if you’re not demanding more from yourself – expanding and learning as you go – you’re choosing a numb existence. You’re denying yourself an extraordinary trip.', author: "Dean Karnazes"},
    {qoute: 'If you don’t have answers to your problems after a four-hour run, you ain’t getting them.', author: "Christopher McDougall"},
    {qoute: 'Pain is temporary. Quitting lasts forever.', author: "Lance Armstrong"},
    {qoute: 'Your body will argue that there is no justifiable reason to continue. Your only recourse is to call on your spirit, which fortunately functions independently of logic.', author: "Tim Noakes"},
    {qoute: 'All I do is keep on running in my own cozy, homemade void, my own nostalgic silence. And this is a pretty wonderful thing. No matter what anybody else says.', author: "Haruki Murakami"},
    {qoute: 'There is something magical about running. after a certain distance, it transcends the body. Then a bit further, it transcends the mind. A bit further yet, and what you have before you, laid bare, is the soul.', author: "Kristin Armstrong"},
    {qoute: 'If you are losing faith in human nature, go out and watch a marathon.', author: "Kathrine Switzer"},
    {qoute: 'There is nothing so momentary as a sporting achievement, and nothing so lasting as the memory of it.', author: "Greg Dening"},
    {qoute: 'Running is real and relatively simple… but it ain’t easy.', author: "Mark Will-Weber"},
    {qoute: 'How to run an ultramarathon? Puff out your chest, put one foot in front of the other, and don’t stop till you cross the finish line.', author: "Dean Karnazes"},
    {qoute: 'Ask nothing from your running, in other words, and you’ll get more than you ever imagined.', author: "Christopher McDougall"},
    {qoute: 'It was being a runner that mattered, not how fast or how far I could run. The joy was in the act of running and in the journey, not in the destination.', author: "John Bingham"},
    {qoute: 'Getting more exercise isn’t only good for your waistline. It’s a natural anti-depressant, that leaves you in a great mood.', author: "Auliq Ice"},
    {qoute: 'Try jogging when following your heart, it’s healthier', author: "Benny Bellamacina"},
    {qoute: 'What I’ve learned from running is that the time to push hard is when you’re hurting like crazy and you want to give up. Success is often just around the corner.', author: "James Dyson"},
    {qoute: 'I’m often asked what I think about as I run. Usually, the people who ask this have never run long distances themselves. I always ponder the question. What exactly do I think about when I’m running? I don’t have a clue.', author: "Haruki Murakami"},
    {qoute: 'But you can’t muscle through a five-hour run that way; you have to relax into it like easing your body into a hot bath, until it no longer resists the shock and begins to enjoy it.', author: "Christopher McDougall"},
    {qoute: 'Adversity causes some men to break; others to break records.', author: "William Arthur Ward"},
    {qoute: 'Every run is a work of art, a drawing on each day’s canvas. Some runs are shouts and some runs are whispers. Some runs are eulogies and others celebrations.', author: "Dagny Scott Barrio"},
    {qoute: 'I run because long after my footprints fade away, maybe I will have inspired a few to reject the easy path, hit the trails, put one foot in front of the other, and come to the same conclusion I did: I run because it always takes me where I want to go.', author: "Dean Karnazes"},
    {qoute: 'My grandmother started walking five miles a day when she was sixty. She’s ninety-seven now, and we don’t know where the heck she is.', author: "Ellen DeGeneres"},
    {qoute: 'An early-morning walk is a blessing for the whole day.', author: "Henry David Thoreau"},
    {qoute: 'If you are in a bad mood go for a walk.If you are still in a bad mood go for another walk.', author: "Hippocrates"},
    {qoute: 'The trouble with jogging is that, by the time you realize you’re not in shape for it, it’s too far to walk back.', author: "Franklin P. Jones"},
    {qoute: 'If you don’t think you were born to run you’re not only denying history. You’re denying who you are.', author: "Christopher McDougall"},
    {qoute: 'Jogging is very beneficial. It’s good for your legs and your feet. It’s also very good for the ground. It makes it feel needed.', author: "Charles M. Schulz"},
    {qoute: 'Yes, I am round. Yes, I am slow. Yes, I run as though my legs are tied together at the knees. But I am running. And that is all that matters.', author: "John Bingham"},
    {qoute: 'But I also realize that winning doesn’t always mean getting first place; it means getting the best out of yourself.', author: "Meb Keflezighi"},
    {qoute: 'The pain of running relieves the pain of living.', author: "Jacqueline Simon Gunn"},
    {qoute: 'I could feel my anger dissipating as the miles went by–you can’t run and stay mad!', author: "Kathrine Switzer"},
    {qoute: 'We wouldn’t be alive without love, we wouldn’t have survived without running. Maybe we shouldn’t be surprised that getting better at one could make you better at the other.', author: "Christopher McDougall"},
    {qoute: 'Winning has nothing to do with racing. Most days don’t have races anyway. Winning is about struggle and effort and optimism, and never, ever, ever giving up.', author: "Amby Burfoot"},
    {qoute: 'All truly great thoughts are conceived while walking.', author: "Friedrich Nietzsche"},
    {qoute: 'The reason we race isn’t so much to beat each other… but to be with each other.', author: "Christopher McDougall"},
                      ];